# -*- coding: utf-8 -*-
"""Preenchimento de Dados Faltantes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mlFQDVhQ02-XCFlvpycEYy_C4-Stnped
"""

import numpy as np
import pandas as pd

baseDeDados = pd.read_csv('/content/drive/MyDrive/Portfólio/Notebooks Python/Bases de Dados/svbr.csv', delimiter=';')
X = baseDeDados.iloc[:,:].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
# Para o imputer funcionar, é necessário que os valores nulos do CSV estejam marcados descritos como nan.
imputer = imputer.fit(X[:,1:3])
# A primeira coluna é de nomes, logo não iremos prenche-la, por isso inicia no 1, e última coluna que iremos preencher é a 2, por isso termina no 3.
X = imputer.transform(X[:,1:3]).astype(str)
X = np.insert(X, 0, baseDeDados.iloc[:,0].values, axis=1)
# Aqui estamos inserindo na base X, uma coluna na posição 0, que será a coluna 0 da baseDeDados.
# O axis=1 indica que a adição é de uma coluna, não linha

print(X)

